config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/show_post/:id', to: "admin#show_post", as: 'admin_post'
  end

  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/u/:id', to: 'users#profile', as: 'user'

  post "u/make_admin" => "users#make_admin"
  post "u/make_user" => "users#make_user"
  delete "u/:id" => "users#destroy"
  
  resources :projects do
    resources :tasks
    resources :orderables, shallow: true
  end

  resources :categories do
    resources :products, shallow: true 
  end

  resources :posts do 
    resources :comments
  end
  
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :body, presence: true, length: { minimum: 10, maximum: 1500 }
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_rich_text :body
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.rich_text_area :body %>
  </div>

  <div>
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <h2><%= post.title %></h2>
  <h4>Posted by <%= link_to post.user.full_name, user_path(post.user), class: "link link-dark" %> </h4>
  <div style="width: 40%">
    <%= post.body %>
  </div>
</div>

app/views/posts/edit.html.erb
  <div class="container">
    <h1>Editing post</h1>

    <%= render "form", post: @post %>

    <br>

    <div>
      <%= link_to "Show this post", @post, class: "btn btn-light btn btn-outline-dark" %> 
      <%= link_to "Back to posts", posts_path, class: "btn btn-light btn btn-outline-dark" %>
    </div>
  </div>

app/views/posts/index.html.erb
<div class="container">
  <div class="container card mt-5 mb-5">
    <h2 class="card-title d-flex justify-content-between mt-3 mb-3"><span>Updates</span>
      <%= link_to "New post", new_post_path, class: "btn btn-dark", style: "top: 50%"%>
    <h2>
    <div id="posts">
      <% @posts.each do |post| %>
        <div style="border: 0.1px solid grey; padding: 1em; margin: 1em; border-radius: 15px;">
          <%= render post %>
        <p>
          <%= link_to "Show this post", post, class: "btn btn-dark" %>
        </p>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Back to posts", posts_path, class: "btn btn-light btn btn-outline-dark" %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mb-3 "style="border: 0.1px solid grey; padding: 1em; margin: 1em; border-radius: 15px;">
  <%= render @post %>
  <div class="btn btn-group">
    <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-light btn btn-outline-dark mb-3" if current_user == @post.user || current_user.admin? %>
    <%= link_to "Back to posts", posts_path, class: "btn btn-light btn-outline-dark mb-3 ms-2" %>

    <%= button_to "Delete this post", @post, method: :delete, class: "btn btn-dark ms-2" if current_user == @post.user || current_user.admin?  %>
  </div>
</div>

<div class="container">
  <div id="options" data-controller="visibility">
    <button data-action="visibility#toggleTargets" class="btn btn-dark">New Comment</button>
    <div data-visibility-target="hideable" hidden><%= render 'comments/form', post: @post, comment: @post.comments.build, label_for_submit: "Reply" %></div>
  </div>
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', post: @post, comment: comment %>
  <% end %>
</div>