config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/show_post/:id', to: "admin#show_post", as: 'admin_post'
  end

  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/u/:id', to: 'users#profile', as: 'user'

  post "u/make_admin" => "users#make_admin"
  post "u/make_user" => "users#make_user"
  delete "u/:id" => "users#destroy"
  
  resources :projects do
    resources :tasks
    resources :orderables, shallow: true
  end

  resources :categories do
    resources :products, shallow: true 
  end

  resources :posts do 
    resources :comments
  end
  
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :image
  has_many :products, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validate :validate_file_type

  def validate_file_type
    return unless image.attached?
    unless image.content_type.in?(%w[image/jpeg image jpg image/png])
      errors.add(:image, "Must be a JPEG, JPG or PNG")
    end
  end


  def image_resized2
    image.variant(resize_to_limit: [300,260]).processed
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @products = @category.products
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description, :image)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>

</div>

app/views/categories/_category_index.html.erb
<div id="<%= dom_id category %>">

  <a href="<%= category_url(category) %>" class="text-decoration-none link link-dark"><%= image_tag(category.image_resized2) %>

  <h3 class="d-flex justify-content-center"> <%= category.name %> </h3>
  </a>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category, class: "btn btn-light btn btn-outline-dark" %> 
  <%= link_to "Back to categories", categories_path, class: "btn btn-light btn btn-outline-dark" %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <br>
  <h2 class="card-title d-flex justify-content-between mt-3 mb-3"><span>Categories</span>
    <%= link_to "New category", new_category_path, class: "btn btn-dark" if current_user.admin? %>
  </h2>
  <br>
  <% @categories.in_groups_of(3, false).each do |group| %>
  <div class="row">
    <% group.each do |category| %>
      <div class="col-md-3 card d-flex justify-content-center ms-2">
          <%= render "category_index", category: category %>
      </div>
    <% end %>
  </div>
<% end %>

<!--  <div id="categories">
    <% @categories.each do |category| %>
      <%= render category %>
      <p>
        <%= link_to "Show this category", category %>
      </p>
    <% end %>
  </div> -->
</div>

app/views/categories/new.html.erb
<div class="container">
  <h1>New category</h1>

  <%= render "form", category: @category %>

  <br>

  <div>
    <%= link_to "Back to categories", categories_path, class: "btn btn-light btn btn-outline-dark" %>
  </div>
</div>

app/views/categories/show.html.erb
<%= render @category %>

<div class="btn btn-group">
  <%= link_to "Edit this category", edit_category_path(@category), class:"btn btn-light btn btn-outline-dark" if current_user.admin? %>
  <%= link_to "Back to categories", categories_path, class:"btn btn-light btn btn-outline-dark ms-2" %>
  <%= button_to "Delete this category", @category, method: :delete, class: "btn btn-dark ms-2" if current_user.admin?%>
  <%= link_to "Create a new product", new_category_product_path(@category), class: "btn btn-dark ms-2" %>
</div>
<div>
  <% @products.each do |product| %>
    <%= render 'products/product_index', locals: { category: @category, product: product } %>
  <% end %>
</div>